remove NP::Iic member
which causes this error on VS:

    crba.hh(75): error C2039: 'Iic' is not a member of 'metapod::NP'

Note that there might be a better way to avoid the error (properly exporting
the symbol or so).

Note also that metapod/tools/has_parent.hh is now unused.